### ISSUE TITLE
PPT update

### ISSUE THREAD

**Issue by LinYeru** [LinYeru/culturalmap#1]
Our presentation ppt has some problems.
1. The website part is not so specific. It needs more details. 
2. It needs to add a little words to describe the pictures inside it for handing in. 
3. A little spelling mistakes.

**Comment by zihanyuann** [comment]
For PPT:
1/Some words to accompany the pictures: Page 7: Data of street art and sculptures/ Page 10: Studio demo photoshoot.
2/I also find several adjustment could be make on the PPT: some Tittle type could be made bigger and some body type could be smaller, so it will be easier for readers to read.

**Comment by XinyanChai** [comment]
According to your comments in presentation, I have make several changes to ppt.
(1) Change the website part in our ppt into three detail part including introduction, interactive timeline and data visualization. 
(2) Put some screen shoot into it and give each screen shoot some description. 
(3) Change some spelling mistake.
