### ISSUE TITLE
Some suggestions about the website

### ISSUE THREAD

**Issue by XinyanChai** [LinYeru/culturalmap#2]
After checking the website, I have some suggestions on our final website submit.
(1) It may be more readable to put the introduction at first than put the timeline.js at the beginning.
(2) The picture in general part should be modified.
(3) The font is a little small and makes the reader look a little uncomfortable.

**Comment by LinYeru** [comment]
I have updated the website according to the suggestions.
1. I changed the logic of website. It has 4 parts now: introduction, instruction, interactive timeline and general. Instruction can show people how to use our physical map. For interactive timeline, when touch, the website(prototype) will change to the specific details information automatically.  In general, people can read the charts for year and space distribution and so on information if they are interested in. 
2.  In general, I add new jquery tool named Chart.js. It displays the charts for year and space distribution with doughnuts, bar and scatterplot. Also it unfolds the arts heatmap and arts position using folium and it unfolds the type information using wordcloud.
3. I changed the main text fonts from 12px to 14px. 

Pictures are newly added for general part. 
![6281607133444_ pic_hd](https://user-images.githubusercontent.com/75267218/101246191-a953b200-3709-11eb-8f12-cb56f410a024.jpg)
![6291607133465_ pic_hd](https://user-images.githubusercontent.com/75267218/101246194-afe22980-3709-11eb-9640-cca05e22d99f.jpg)
![1311607180052_ pic_hd](https://user-images.githubusercontent.com/75267218/101246204-bffa0900-3709-11eb-93fc-e458b7f3684e.jpg)
