### ISSUE TITLE
Group Report Changes

### ISSUE THREAD

**Issue by zihanyuann** [LinYeru/culturalmap#3]
Some issues for the group report draft:
1/ Context could be discussed more clearly
2/ More details could be added to the Interactive Screen part of the Design Process part
3/ Proper styles could be chosen to optimize the reading proces

**Comment by WenyunDeng** [comment]
Maybe in the reflection we can report that we can add more data of the artworks to enrich their information and deliver more information to the audience through the Web or other means.

**Comment by XinyanChai** [comment]
After reading the draft essay, I have some suggestions
(1) spelling mistakes (I have changed some of it)
(2) I think it still needs to add some reference in our introduction part.
(3) Content part can be written in the prototype part.
(4) Add some legend.

**Comment by zihanyuann** [comment]
Adjustments log:
1/ More details were added to the interactive website part
2/ Grammar were checked again and improved the spellings.
3/ Context were devised to provide more cohesion.

**Comment by WenyunDeng** [comment]
For the several parts of the design process, physical maps, web pages, and the interaction between people and these two. The structure of the report needs slightly adjusted, and some descriptions of the production process and usage process are added.
